#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove mesh and time directories
cleanCase

# Remove 0 directory
\rm -rf 0

#------------------------------------------------------------------------------
