#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set up initial conditions
echo "Copying initial to 0"
cp -r initial 0

# Create the mesh
runApplication blockMesh

# Set phase field
runApplication setFields

# Run the solver
if [[ "$1" == "parallel" ]]; then
    # Run in parallel                                                                                                                                                                                       
    runApplication decomposePar
    mpirun -np 6 beamWeldFoam -parallel &> log.beamWeldFoam
    runApplication reconstructPar
else
    # Run in serial                                                                                                                                                                            
    runApplication beamWeldFoam
fi

#------------------------------------------------------------------------------
